### ISSUE TITLE
Question - Is there a default set for modded races?

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [ColonolNutty/MoreFarmingFU#3]
I play FU with all Frackin Races available mods does your mod have a default for mods not yet added to "yes chef?"

**Comment by ColonolNutty** [comment]
Default?

**Comment by ColonolNutty** [comment]
Other than that, I'm not sure what you mean by default

**Comment by ColonolNutty** [comment]
Closing due to unanswered questions
